### ISSUE TITLE
scipy.optimize.newton_krylov failed for very small wilson coefficient

### ISSUE THREAD

**Issue by haolinli1991** [wilson-eft/wilson#44]
Hi,
I encounter a problem when use Wilson matching and run the SMEFT parameter.

Following code will generate error
`smeft_input = {"phil3_12": 1/((2000.)**2)}
   w = Wilson(smeft_input,scale = Lambda,eft = 'SMEFT', basis = 'Warsaw')
    w.set_option('smeft_accuracy','leadinglog')
    wc = w.match_run(scalein,'WET','flavio')
`

:
/home/haolinli/.local/lib/python3.6/site-packages/scipy/optimize/nonlin.py:475: RuntimeWarning: invalid value encountered in double_scalars
  and dx_norm/self.x_rtol <= x_norm))
/home/haolinli/.local/lib/python3.6/site-packages/scipy/sparse/linalg/isolve/_gcrotmk.py:131: RuntimeWarning: invalid value encountered in cdouble_scalars
  alpha = 1/hcur[-1]
/home/haolinli/.local/lib/python3.6/site-packages/wilson/run/smeft/smpar.py:72: Warning: Standard optimization method did not converge. The GMRES method is used instead.
  warnings.warn('Standard optimization method did not converge. The GMRES method is used instead.', Warning)
Traceback (most recent call last):
  File "/home/haolinli/.local/lib/python3.6/site-packages/wilson/run/smeft/smpar.py", line 70, in vMh2_to_m2Lambda
    xres = scipy.optimize.newton_krylov(f0, x0)
  File "<string>", line 8, in newton_krylov
  File "/home/haolinli/.local/lib/python3.6/site-packages/scipy/optimize/nonlin.py", line 315, in nonlin_solve
    raise ValueError("Jacobian inversion yielded zero vector. "
ValueError: Jacobian inversion yielded zero vector. This indicates a bug in the Jacobian approximation.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/haolinli/.local/lib/python3.6/site-packages/wilson/run/smeft/smpar.py", line 75, in vMh2_to_m2Lambda
    f_tol=1e-7)
  File "<string>", line 8, in newton_krylov
  File "/home/haolinli/.local/lib/python3.6/site-packages/scipy/optimize/nonlin.py", line 315, in nonlin_solve
    raise ValueError("Jacobian inversion yielded zero vector. "
ValueError: Jacobian inversion yielded zero vector. This indicates a bug in the Jacobian approximation.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scan_SMEFT.py", line 129, in <module>
    print(abs(epssmumu(SMEFTWC_list[121],2000.))) 
  File "scan_SMEFT.py", line 68, in epssmumu
    wc = w.match_run(scalein,'WET','flavio')
  File "/home/haolinli/.local/lib/python3.6/site-packages/wilson/classes.py", line 224, in match_run
    smeft = SMEFT(self.wc.translate('Warsaw', parameters=self.parameters))
  File "/home/haolinli/.local/lib/python3.6/site-packages/wilson/run/smeft/classes.py", line 35, in __init__
    self._set_initial_wcxf(wc, get_smpar=get_smpar)
  File "/home/haolinli/.local/lib/python3.6/site-packages/wilson/run/smeft/classes.py", line 78, in _set_initial_wcxf
    self.C_in.update(self._get_sm_scale_in())
  File "/home/haolinli/.local/lib/python3.6/site-packages/wilson/run/smeft/classes.py", line 195, in _get_sm_scale_in
    return self._run_sm_scale_in(C_out, scale_sm=scale_sm)
  File "/home/haolinli/.local/lib/python3.6/site-packages/wilson/run/smeft/classes.py", line 152, in _run_sm_scale_in
    C_SM = smpar.smeftpar(scale_sm, C_out, basis='Warsaw')
  File "/home/haolinli/.local/lib/python3.6/site-packages/wilson/run/smeft/smpar.py", line 110, in smeftpar
    _d = vMh2_to_m2Lambda(v=v, Mh2=Mh**2, C=C)
  File "/home/haolinli/.local/lib/python3.6/site-packages/wilson/run/smeft/smpar.py", line 77, in vMh2_to_m2Lambda
    raise ValueError("No solution for m^2 and Lambda found. This problem can be caused by very large values for one or several Wilson coefficients.")
ValueError: No solution for m^2 and Lambda found. This problem can be caused by very large values for one or several Wilson coefficients.

It seems that this error is because C is too small, probably adding some protection avoiding vMh2_to_m2Lambda going to non-zero C for extremely small C will fix the problem.

Best,
Haolin

**Comment by DavidMStraub** [comment]
It's simply an unphysical point in WC parameter space.

**Comment by haolinli1991** [comment]
> It's simply an unphysical point in WC parameter space.

OK, I see, it will destabilize the Higgs potential generating a positive C['phi']. Thanks a lot
